/**:
  ros__parameters:
    odom_frame: "odom"
    base_link_frame: "base_link"
    if_name: "can0"
    tf_used: true
    wheel_base: 0.66

    io_cmd:
      enable: false
      lower_beam: false
      upper_beam: false
      turn_lamp: 0
      braking_lamp: false
      clearance_lamp: false
      fog_lamp: false
      speaker: false
      discharge: false

    ultrasonic_number: [0, 1, 2, 3, 4, 5, 6, 7]
